<?php
	echo("<div class='container'>");
    echo("<h1>Perguntas Frequentes</h1>");
	echo("<div class='col-md-10'>");
	echo("<ol>");
	echo("<li><p>O que são atividades complementares?</p></li>");
	echo("<p>São atividades referentes a habilidades, conhecimentos, competências e atitudes adquiridas fora do ambiente escolar que visam ao enriquecimento do aluno, alargando o seu currículo com experiências e vivências acadêmicas internas ou externas ao curso. Embora não façam parte das disciplinas que os alunos devem cursar, são consideradas diretamente pertinentes à sua formação, tais como atividades de extensão, pesquisa, iniciação à docência, participação em eventos, publicações e vivência profissional complementar.</p>");
	echo("<li><p>Quem é obrigado a realizar atividades complementares?</p></li>");
	echo("<p>Todo aluno matriculado deve realizar as atividades complementares, sob pena de não conseguir colar grau ao final do curso.</p>");
	echo("<li><p>Quantas horas de atividades complementares devem ser realizadas?</p></li>");
	echo("<p>Cada curso e faculdade têm suas próprias requisições.</p>");
	echo("<li><p>Quais atividades são consideradas complementares?</p></li>");
	echo("<p>São atividades complementares:</p>");
	echo("<ul>");
	echo("<li><p>Participação em atividades de iniciação à docência e pesquisa, como monitoria, pesquisas e projetos institucionais, grupos de estudo ou pesquisa sob supervisão de professores ou alunos do mestrado ou do doutorado e de leitura, sob a supervisão de professor ou mestrando ou doutorando (neste caso com prévia comunicação à Coordenação);</p></li>");
	echo("<li><p>Assistência de congressos, seminários, conferências, palestras, defesas de dissertação de mestrado e tese de doutorado, e eventos, mostras, exposições complementares à formação;</p></li>");
	echo("<li><p>Publicação de artigos, realização de monografias (não curriculares), apresentação de trabalhos em eventos científicos e participação com trabalhos em concursos, exposições e mostras;</p></li>");
	echo("<li><p>Atividades de vivência profissional complementar, como realização de estágios não curriculares, participação em projetos sociais e participação em oficinas de leitura sob supervisão de professor, mestrando ou doutorando;</p></li>");
	echo("<li><p>Atividades de extensão, como cursos “ um exemplo são os cursos da Instituição Cursos Online SP do Brasil ” e disciplinas cursadas em programas de extensão.</p></li>");
	echo("<li><p>Outras atividades expressamente pré-autorizadas pela Coordenação de Atividades Complementares.</p></li>");
	echo("</ul>");
	echo("<li><p>Quais atividades não são consideradas complementares?</p></li>");
	echo("<p>Não são atividades complementares, entre outras:</p>");
	echo("<ul>");
	echo("<li><p>Cursos de competências sem vinculação direta ao curso (exemplo: você cursa Direito e apresenta como atividade complementar um curso de Geografia);</p></li>");
	echo("<li><p>Palestras e seminários com tema que não se enquadrem no conteúdo programático das disciplinas do curso;</p></li>");
	echo("<li><p>Vivência profissional não complementar;</p></li>");
	echo("<li><p>Palestras e seminários sem ligação direta com a formação desejada.</p></li>");
	echo("</ul>");
	echo("<li><p>O Estágio Supervisionado e as atividades dele decorrentes podem ser computados como atividade complementar?</p></li>");
	echo("<p>Não. O Estágio Supervisionado é carga horária curricular, portanto não pode ser considerado complementar.</p>");
	echo("<li><p>Posso realizar um único tipo de atividade?</p></li>");
	echo("<p>Não. As atividades são classificadas em categorias e para cada categoria há um limite máximo de horas que podem ser computadas.</p>");
	echo("<li><p>Posso realizar atividades já no primeiro período?</p></li>");
	echo("<p>Sim, as atividades podem ser realizadas a partir da matrícula.</p>");
	echo("<li><p>Posso realizar atividades durante as férias?</p></li>");
	echo("<p>Sim, as atividades podem ser realizadas durante as férias.  Mas mesmo durante as férias devem ser respeitados os prazos e procedimentos para sua realização.</p>");
	echo("<li><p>Quantas horas são atribuídas por atividade?</p></li>");
	echo("<p>O critério de atribuição padrão é o tempo efetivamente despendido pelo aluno para a realização da atividade.  Quando não houver descrição do número de horas no requerimento de autorização nem na comprovação da realização da atividade, a Coordenação de Atividades Complementares fixará por estimativa. Algumas atividades institucionais já têm número de horas pré-fixado, assim como certas atividades pré-autorizadas pela Coordenação de Atividades Complementares.</p>");
	echo("<li><p>Há um máximo de horas que pode ser obtido por atividade?</p></li>");
	echo("<p>Há um limite máximo de horas que pode ser computado para cada categoria. Cada curso e faculdade têm suas próprias requisições.</p>");
	echo("<li><p>Quantos horas equivalem a um crédito?</p></li>");
	echo("<p>Cada curso e faculdade têm suas próprias requisições.</p>");
	echo("<li><p>Qual é o procedimento para o cômputo das horas de atividades complementares?</p></li>");
	echo("<p>O procedimento padrão de cômputo das horas, que pode variar dependendo do tipo de atividade, se dá em duas etapas.  A primeira é um pedido prévio de autorização para a realização da atividade.  A segunda etapa é a posterior comprovação de realização da atividade, normalmente através da apresentação de um relatório.</p>");
	echo("<li><p>Todas as atividades exigem apresentação de relatório para comprovação da realização da atividade?</p></li>");
	echo("<p>Não.  A forma de comprovação da realização da atividade varia dependendo do tipo de atividade:</p>");
	echo("<ul>");
	echo("<li><p>Participação em monitoria, pesquisas e projetos institucionais ou integrados, grupos de estudo ou pesquisa supervisionado: Relatório subscrito pelo Professor Orientador, com atribuição de carga horária;</li></p>");
	echo("<li><p>Assistência de congressos, seminários, conferências, palestras, eventos culturais complementares à formação, mostras, exposições e defesas de dissertação de mestrado e tese de doutorado: Relatório do aluno e certificado de presença (com atribuição de carga horária);</li></p>");
	echo("<li><p>Publicação de artigo, livro ou capítulo de livro, realização de monografias não curriculares, apresentação de trabalhos em eventos científicos, participação em concursos, exposições e mostras ou produção técnica em multimídia: artigo publicado, monografia produzida, produto desenvolvido ou trabalho apresentado;</li></p>");
	echo("<li><p>Realização de estágios não curriculares: relatório do aluno e atestado de realização (com atribuição de carga horária)</li></p>");
	echo("<li><p>Cursos extracurriculares e disciplinas cursadas em programas de extensão: certificado de realização (com atribuição de carga horária), “ um exemplo são os certificados da Instituição Cursos Online SP do Brasil ”</li></p>");
	echo("</ul>");
	echo("<li><p>Qual o prazo para a comprovação da realização da atividade?</p></li>");
	echo("<p>A comprovação, normalmente através de relatório e atestado de realização (com atribuição de carga horária), deve ser apresentada em até 30 (trinta) dias após o término da atividade, conforme constar do pedido de autorização.</p>");
	echo("<li><p>Como deve ser apresentado o relatório?</p></li>");
	echo("<p>O relatório, quando exigido, deve conter identificação do aluno, indicação da natureza da atividade, seus participantes, seu local e sua data, e sua duração.</p>");
	echo("<p>Além disso, o relatório deve conter descrição pormenorizada dos fatos envolvidos na própria atividade, o que varia dependendo de sua natureza.  Por exemplo, o relatório de estágio deve conter os atos que costumam ser realizados pelo estagiário, o relatório de palestra deve conter uma resenha do que foi apresentado, e assim por diante.</p>");
	echo("<p>O relatório será rejeitado se for considerado insuficiente para demonstrar que o aluno atendeu integralmente à atividade ou pode ser conferida carga horária inferior tendo em vista critérios de desempenho e qualidade.  Os casos de identificação de plágio de relatório são encaminhados à comissão disciplinar, para a aplicação das sanções cabíveis, que podem chegar a suspensão e jubilamento.</p>");
	echo("<li>O que deve ser anexado ao relatório?</li>");
	echo("<p>Devem ser anexados ao relatório os documentos comprobatórios da realização da atividade, conforme exigido pelo regulamento para cada tipo de atividade, como por exemplo, o certificado de presença em congresso ou seminário, o atestado de realização de estágio etc.</p>");
	echo("</ol>");
	echo("</div>");
	echo("<div class='col-md-2'></div>");
	echo("</div>");
?>
